// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004040756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("ef684ba0-0ad5-41d1-8223-4122c149f9da"),
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = new Guid("ad914740-7d42-4374-83a0-6b939e2f1f05"),
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = new Guid("f6564641-ad62-41d0-9778-f289d6d434be"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("3c16db02-611f-40cd-ba34-43cc493ac676"),
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("08852737-942a-48e2-8622-6654af313a09"),
                            CountryName = "China"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("9403db58-adc5-494b-a455-b075aa7cfc46"),
                            Address = "913 Main St, Cityville",
                            CountryId = new Guid("08852737-942a-48e2-8622-6654af313a09"),
                            DateOfBirth = new DateOnly(1962, 11, 25),
                            Email = "alice.johnson@example.com",
                            Gender = "Other",
                            PersonName = "Alice Johnson",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("cd6f6dfa-71cf-4f74-ab7d-5359ac17bbea"),
                            Address = "332 Main St, Cityville",
                            CountryId = new Guid("9a1f995b-fbab-4612-9e9c-358048815dba"),
                            DateOfBirth = new DateOnly(2004, 3, 5),
                            Email = "bob.smith@example.com",
                            Gender = "Male",
                            PersonName = "Bob Smith",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("210780c5-945e-4a1c-9287-f5dee8e67e53"),
                            Address = "688 Main St, Cityville",
                            CountryId = new Guid("5ca1618f-97c6-46b0-8a72-6c312a339954"),
                            DateOfBirth = new DateOnly(2005, 8, 29),
                            Email = "carlos.rivera@example.com",
                            Gender = "Female",
                            PersonName = "Carlos Rivera",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
